# Autogenerated wrapper script for boost_jll for x86_64-linux-gnu-cxx11
export libboost_atomic, libboost_chrono, libboost_container, libboost_context, libboost_contract, libboost_coroutine, libboost_date_time, libboost_filesystem, libboost_graph, libboost_iostreams, libboost_log, libboost_log_setup, libboost_prg_exec_monitor, libboost_program_options, libboost_random, libboost_regex, libboost_serialization, libboost_stacktrace_basic, libboost_stacktrace_noop, libboost_system, libboost_thread, libboost_timer, libboost_type_erasure, libboost_unit_test_framework, libboost_wave, libboost_wserialization

JLLWrappers.@generate_wrapper_header("boost")
JLLWrappers.@declare_library_product(libboost_atomic, "libboost_atomic.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_chrono, "libboost_chrono.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_container, "libboost_container.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_context, "libboost_context.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_contract, "libboost_contract.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_coroutine, "libboost_coroutine.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_date_time, "libboost_date_time.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_filesystem, "libboost_filesystem.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_graph, "libboost_graph.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_iostreams, "libboost_iostreams.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_log, "libboost_log.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_log_setup, "libboost_log_setup.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_prg_exec_monitor, "libboost_prg_exec_monitor.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_program_options, "libboost_program_options.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_random, "libboost_random.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_regex, "libboost_regex.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_serialization, "libboost_serialization.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_stacktrace_basic, "libboost_stacktrace_basic.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_stacktrace_noop, "libboost_stacktrace_noop.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_system, "libboost_system.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_thread, "libboost_thread.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_timer, "libboost_timer.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_type_erasure, "libboost_type_erasure.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_unit_test_framework, "libboost_unit_test_framework.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_wave, "libboost_wave.so.1.76.0")
JLLWrappers.@declare_library_product(libboost_wserialization, "libboost_wserialization.so.1.76.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libboost_atomic,
        "lib/libboost_atomic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_chrono,
        "lib/libboost_chrono.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_container,
        "lib/libboost_container.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_context,
        "lib/libboost_context.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_contract,
        "lib/libboost_contract.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_coroutine,
        "lib/libboost_coroutine.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_date_time,
        "lib/libboost_date_time.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_filesystem,
        "lib/libboost_filesystem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_graph,
        "lib/libboost_graph.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_iostreams,
        "lib/libboost_iostreams.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_log,
        "lib/libboost_log.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_log_setup,
        "lib/libboost_log_setup.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_prg_exec_monitor,
        "lib/libboost_prg_exec_monitor.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_program_options,
        "lib/libboost_program_options.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_random,
        "lib/libboost_random.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_regex,
        "lib/libboost_regex.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_serialization,
        "lib/libboost_serialization.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_stacktrace_basic,
        "lib/libboost_stacktrace_basic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_stacktrace_noop,
        "lib/libboost_stacktrace_noop.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_system,
        "lib/libboost_system.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_thread,
        "lib/libboost_thread.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_timer,
        "lib/libboost_timer.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_type_erasure,
        "lib/libboost_type_erasure.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_unit_test_framework,
        "lib/libboost_unit_test_framework.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_wave,
        "lib/libboost_wave.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_wserialization,
        "lib/libboost_wserialization.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
